/**
 * Static set of Infinite Flight 3D airport ICAO codes.
 * These airports have photoreal / 3D scenery in Infinite Flight.
 */
export const IF_3D_AIRPORTS = new Set([
  // ── North America ──────────────────────────────
  'KATL', 'KDEN', 'KDFW', 'KJFK', 'KLAX', 'KLAS', 'KLGA', 'KMDW', 'KMIA', 'KMSP',
  'KORD', 'KPHX', 'KSEA', 'KSFO', 'KEWR', 'KBOS', 'KIAD', 'KDTW', 'KFLL', 'KPHL',
  'KHOU', 'KSNA', 'KSAN', 'PHNL', 'PANC', 'KSJU', 'KOAK', 'KPDX', 'KSLC', 'KBWI',
  'KSTL', 'KCLE', 'KCLT', 'KTPA', 'KPIT', 'KAUS', 'KMCI', 'KRDU', 'KMKE', 'KONT',
  'KBUR', 'KLGB', 'KVNY', 'KSMF', 'KSJC', 'KSBD', 'KPSP', 'KFAT', 'KRNO', 'KPHF',
  'KVGT', 'KNUC', 'KMYR', 'KILM', 'KCHS', 'KJAX', 'KOPF', 'KMCO', 'KPBI', 'KRSW',
  'CYYZ', 'CYVR', 'CYUL', 'CYYC', 'CYEG', 'CYWG', 'CYOW', 'CYHZ', 'CYXE', 'CYYJ',
  'MMMX', 'MMGL', 'MMTY', 'MMTJ', 'MMPR', 'MMUN', 'MMSM', 'MMCZ', 'MMCU', 'MMAS',
  // ── Caribbean & Central America ────────────────
  'MROC', 'MPTO', 'MBPV', 'MKJP', 'MDPP', 'TNCM', 'TTPP', 'TBPB', 'TXKF',
  'MGTK', 'MSSS', 'MNMG', 'MHLM', 'MHRO',
  // ── Europe ─────────────────────────────────────
  'EGLL', 'EGKK', 'EGGW', 'EGLC', 'EGSS', 'EGCC', 'EGPH', 'EGNX', 'EGBB',
  'EGTE', 'EGHI', 'EGPA', 'EGPD', 'EGPE', 'EGNT', 'EGPF', 'EGAC',
  'EIDW', 'EINN', 'EIKN',
  'EDDM', 'EDDF', 'EDDH', 'EDDB', 'EDDS', 'EDDK', 'EDDL', 'EDDN', 'EDDC', 'EDDT',
  'EHAM', 'EHRD', 'EHBK', 'EHTX',
  'EBBR', 'EBCI', 'ELLX',
  'LFPG', 'LFPO', 'LFLL', 'LFMN', 'LFBO', 'LFSB', 'LFRN', 'LFRS', 'LFBD', 'LFBZ',
  'LFML', 'LFMP', 'LFMK', 'LFMT', 'LFJL', 'LFLY', 'LFPB',
  'LEMD', 'LEBL', 'LEPA', 'LEAL', 'LEBB', 'LEMG', 'LEZL', 'LEVX', 'LEST', 'LEAM',
  'GCLP', 'GCFV', 'GCTS', 'GCLA', 'GCHI', 'GCXO', 'GCRR',
  'LPPT', 'LPFR', 'LPPR', 'LPPD', 'LPLA',
  'LIRF', 'LIMC', 'LIME', 'LIPZ', 'LIPE', 'LIML', 'LICJ', 'LICC', 'LICA', 'LICT',
  'LIBP', 'LIBD', 'LICZ', 'LIEE', 'LIRQ', 'LIRP', 'LIRN', 'LIRG', 'LIBR',
  'LSZH', 'LSGG', 'LSZA', 'LSMM', 'LSME',
  'LOWW', 'LOWI', 'LOWS', 'LOWL', 'LOGG', 'LOAN',
  'EPWA', 'EPKK', 'EPGD', 'EPPO', 'EPWR', 'EPSC', 'EPKT',
  'LKPR', 'LKTB', 'LKVO',
  'LHBP', 'LHDC',
  'LTBA', 'LTAI', 'LTFM', 'LTFE', 'LTBS', 'LTAC', 'LTCG', 'LTBJ', 'LTAN', 'LTBL',
  'LTBH', 'LTBD', 'LTBG',
  'LGAV', 'LGTS', 'LGKR', 'LGRP', 'LGHI', 'LGIO',
  'ENGM', 'ENBO', 'ENBR', 'ENZV', 'ENTC', 'ENCN', 'ENAT', 'ENFL', 'ENKB',
  'EKCH', 'EKBI', 'EKAH', 'EKAT',
  'ESGG', 'ESSA', 'ESMS', 'ESCM', 'ESPA', 'ESST', 'ESDF', 'ESUT',
  'EFHK', 'EFTU', 'EFRO', 'EFOU', 'EFIV', 'EFJY',
  'GMMN', 'GMME', 'GMTT', 'GMFM', 'GMFN', 'GMMX', 'GMMC',
  'DTTA', 'DTMB', 'DTTJ', 'DTTZ', 'DTTB',
  'HLLT', 'HLGN', 'HLLM',
  // ── Middle East ────────────────────────────────
  'OMDB', 'OMDW', 'OMAA', 'OMAD', 'OMAL', 'OMSJ', 'OMFJ', 'OMRK',
  'OEJD', 'OEMA', 'OEDF', 'OEYN', 'OESH', 'OERK', 'OETB', 'OEAB', 'OETF', 'OEGN',
  'OKBK',
  'ORBI', 'ORBB', 'ORMM', 'ORER',
  'LLBG',
  'OTHH', 'OTBD',
  'OYAA', 'OYSN', 'OYAB',
  'OIIE', 'OIIP', 'OIII', 'OIFM', 'OIKB', 'OISS',
  'OLBA',
  // ── Africa ─────────────────────────────────────
  'HAAB', 'HECA', 'HKJK', 'HSSS', 'HSPN',
  'FALE', 'FACT', 'FAOR', 'FAPE', 'FABS', 'FABB',
  'DXXX', 'DIAP', 'GOOY', 'GVNP', 'GUCY',
  'FBSK', 'FMMI', 'FYWH', 'FQMA', 'FLKK', 'FWKI',
  // ── Asia ───────────────────────────────────────
  'VHHH', 'VMMC',
  'WSSS', 'WMKK', 'WMKP', 'WMSA', 'WBSB',
  'WIII', 'WADD', 'WIDD', 'WIPL', 'WIHH', 'WRLL', 'WAMM',
  'RPLL', 'RPVM', 'RPVF', 'RPMD', 'RPLB', 'RPUB',
  'VTBS', 'VTBD', 'VTCC', 'VTSP', 'VTSM', 'VTUO', 'VTCH', 'VTUK',
  'RKSI', 'RKSS', 'RKPK', 'RKNW', 'RKPU', 'RKTN',
  'RCTP', 'RCSS', 'RCKH', 'RCMQ',
  'RJTT', 'RJBB', 'RJAA', 'RJCC', 'RJOO', 'RJNS', 'RJFU', 'RJSS', 'RJFF',
  'RJGG', 'RJSN', 'RJNT', 'RJOK', 'RJDC', 'RJFR', 'RJNA',
  'VABB', 'VIDP', 'VOHS', 'VOMM', 'VECC', 'VOCB', 'VOBL', 'VOGO', 'VAAH',
  'ZBAA', 'ZBYN', 'ZSPD', 'ZSSS', 'ZGGG', 'ZUUU', 'ZUCK', 'ZHCC', 'ZLXY', 'ZHHH',
  'ZSAM', 'ZJHK', 'ZSHC', 'ZBTJ', 'ZGHA', 'ZPPP', 'ZGSZ', 'ZUGY', 'ZLLL', 'ZBHH',
  'UHWW', 'UUDD', 'UUWW', 'URSS', 'ULLI', 'UWKD', 'USHH', 'UNNT',
  'VDPP', 'VDSR',
  'VVTS', 'VVNB', 'VVDN', 'VVPQ', 'VVCR', 'VVCA',
  'VGHS', 'VEBD', 'VGUV',
  'OPKC', 'OPLH', 'OPLA', 'OPIS', 'OPPS',
  // ── Oceania ────────────────────────────────────
  'YSSY', 'YMML', 'YBBN', 'YPAD', 'YPPH', 'YPDN', 'YBCS', 'YBTL', 'YSCB',
  'YBMC', 'YSBK', 'YMLT', 'YMHB', 'YPKG',
  'NZAA', 'NZCH', 'NZWN', 'NZQN', 'NZNP', 'NZDN',
  'NFFN', 'NGTA', 'NGFU', 'NWWW', 'NVVV',
  // ── South America ──────────────────────────────
  'SBGR', 'SBKP', 'SBGL', 'SBPA', 'SBBR', 'SBCF', 'SBFL', 'SBRF', 'SBSV',
  'SBCT', 'SBSP', 'SBBE', 'SBEG', 'SBCY', 'SBMN',
  'SEQM', 'SEGU', 'SENL', 'SECU',
  'SKBO', 'SKBQ', 'SKCL', 'SKMD', 'SKRG',
  'SCEL', 'SCFA', 'SCTE',
  'SAEZ', 'SABE', 'SAME', 'SACO', 'SAWH', 'SARI', 'SARC',
  'SPJC', 'SPIM', 'SPZO', 'SPHI', 'SPQU',
  'SVMI', 'SVBS',
  'SMJP',
]);
